cascadiajs/2015.cascadiajs.com

COC.md

This patch contains spelling / grammar / rewording fixes. 
To think about:
* Would it be possible to have an old fashioned callable-type telephone number too? (It appears that the phone number will only be textable.)
* Can we put a linked TOC at the top so that - in a heated situation - it's as easy as possible to find the contact details?

Spelling / grammar fixes.

---

proposals/README.md

@crtr0 @KatieK2 @alexlande @ryan-roemer 
Please review. Let me know what works, what needs fixin', what sounds crazy.

Create CFP that covers all of CJSFest and move from repo

---

public/index.ejs

Fix a resort name typo

---

proposals/README.md

Make sure the links and the headers in the Markdown show properly.

Markdown Cleanup

---

README.md

- Move actionable info to the top :tada:
- Link to CFP markdown
- Update ticket info

Update CFP section in README.md

---

README.md
package.json
public/_partials/footer.ejs
public/_partials/newsletter.ejs
public/_partials/tickets/soon.ejs
public/assets/css/style.less

Also add Ticket sale date and add Zach as author

responsive changes to handle different sizes better

---

public/index.ejs

These changes adjust to current ticket sales and modifies the wording for the button slightly.

Change partial to on sale

---

proposals/free_ideas/A History of Node.md
proposals/free_ideas/README.md

Feedback from https://github.com/cascadiajs/2015.cascadiajs.com/issues/84 was positive.

Created "free ideas" readme and added one.

---

proposals/free_ideas/Cross Platform Browser Extensions.md

convert #78 into a free proposal

---

proposals/README.md

Update to reflect CascadiaCSS and some updates.

---

public/_layout.ejs

This is just a small commit to make sure I have the PR flow down.
Web Content Accessibility Guidelines suggest making it easy for computers and users to know "the default human language of each Web page" — http://www.w3.org/TR/WCAG20/#meaning

Add lang attribute to HTML tag

---

COC.md

particpants => participants
inculdes => includes

Fixed a few minor typos.

---

public/assets/css/style.less

Per @hackygolucky requests trying out some em based alignments and centered text.

Some little tweaks

---

public/404.ejs
public/_data.json
public/assets/css/style.less

This adds a basic 404 page design. Now that we've got multiple pages, the likelihood of hitting a 404 has risen substantially (I say this because I type things wrong a lot and have already hit it several times).
Screenshot:
/cc @davethegr8 @zachattack

Feature: Add 404 page design

---

public/news/_data.json
public/news/_layout_speaker.ejs
public/news/intro-gregor-adams.md

This adds an introducing blog post for Gregor Adams. Our first CSS post!
I've got a tweet ready to go in the spreadsheet as well.

Feature: introducing gregor

---

public/news/_data.json
public/news/intro-jeff-lembeck.md

This adds an introducing post for Jeff Lembeck.

Feature: introducing jeff

---

public/news/_data.json
public/news/intro-jeff-lembeck.md
public/news/intro-shay-howe.md

This adds an introducing post for Shay Howe.
I branched this off of `feature-introducingJeff` because I didn't want to deal with merge conflicts in the data json. Merge that one first, then this one!

Feature introducing shay

---

public/news/_data.json
public/news/intro-ricardo-vazquez.md

Feature: Add introducing ricardo post

---

public/_partials/footer.ejs
public/index.ejs
public/speakers/_partials/poloroid.ejs

This adds a quick random speaker display to the homepage. Picks a random speaker for each day + displays them. All of the speakers are in the page HTML but are hidden by default.

Feature: speaker rotation

---

public/_data.json
public/assets/css/style.less

This removes some redundant CSS + JSON for the homepage speaker display.
/cc @davethegr8

Chore: Fix homepage speaker preview css bug

---

website/public/news/_data.json
website/public/news/intro-rachel-nabors.md

Feature: Add introducing Rachel Nabors post

---

website/public/news/_data.json
website/public/news/intro-alan-mooiman.md

Adds an introducing blog post for Alan.

Feature: Add introducing alan post

---

website/public/_partials/day/speakers.ejs
website/public/_partials/schedule/talk.ejs
website/public/assets/css/_include/schedule.less
website/public/assets/css/_include/variables.less
website/public/assets/css/style.less
website/public/css/_schedule.ejs

my take on the schedule approach. pass number one. @davethegr8 for review

schedule page styles

---

website/public/news/_data.json
website/public/news/css-layer-tennis.md

This adds a post with details about CSS Layer Tennis to the news page. Progress!
/cc @davethegr8 @thisisjohnbrown

Feature: Add Layer Tennis post
